const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');const root=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(root+'/data/vocab.json'));
class El{constructor(){this.children=[];this.events={};this.dataset={};this.classList={add(){},remove(){},toggle(){}};this.textContent='';this.value='';}querySelector(s){this.childrenByName??={};return this.childrenByName[s]??=(new El())}appendChild(c){this.children.push(c)}replaceChildren(){this.children=[]}addEventListener(e,f){this.events[e]=f}click(){this.events.click?.({target:this,stopPropagation(){}})}}
const jong=s=>(s.charCodeAt(s.length-1)-0xac00)%28!==0;
async function boot(file){const els=new Map(),toggles=['time','place','object','question'].map(x=>{const e=new El();e.dataset.element=x;return e}),get=id=>{if(!els.has(id))els.set(id,new El());return els.get(id)},calls=[];const ctx={console,document:{getElementById:get,querySelectorAll:()=>toggles,createElement:()=>new El()},App:{loadVocab:async()=>data,particleIGa:s=>jong(s)?'이':'가',particleEulReul:s=>jong(s)?'을':'를',pulseBlock(){},speakSentence:p=>calls.push(p),speak:s=>calls.push([s])}};vm.createContext(ctx);await vm.runInContext(fs.readFileSync(root+'/js/'+file,'utf8'),ctx);return{get,toggles,calls}}
(async()=>{let b=await boot('action-builder.js');assert.equal(b.get('subject-select').children.length,11);const select=(id,value)=>{const e=b.get(id);e.value=String(value);e.events.change()};const subjects=data.action.subjects,verbs=data.action.verbs;for(const [kr,verb,expected] of [['가족은','마시다','가족은 무엇을 마셔요?'],['부모님은','먹다','부모님은 무엇을 먹어요?'],['친구는','하다','친구는 무엇을 해요?']]){select('subject-select',subjects.findIndex(x=>x.kr===kr));select('verb-select',verbs.findIndex(x=>x.id===verb));const q=b.toggles.find(x=>x.dataset.element==='question');if(!b.get('full-sentence').textContent.endsWith('?'))q.click();assert.equal(b.get('full-sentence').textContent,expected);b.get('speak-btn').click();assert.deepEqual(b.calls.at(-1).join(' '),expected)}
b.toggles.find(x=>x.dataset.element==='time').click();assert.equal(b.get('full-sentence').textContent,'친구는 무엇을 해요?');select('verb-select',verbs.findIndex(x=>x.id==='가다'));assert.equal(b.toggles.find(x=>x.dataset.element==='question').disabled,true);assert.ok(!b.get('full-sentence').textContent.includes('무엇을'));
const before=b.get('subject-select').value;b.get('block-subject').click();assert.notEqual(String(b.get('subject-select').value),String(before));assert.equal(new Set(subjects.map(x=>x.kr)).size,11);for(const kr of ['가족은','부모님은','친구는'])assert.ok(subjects.some(s=>s.kr===kr));
select('subject-select',subjects.findIndex(x=>x.kr==='친구는'));select('verb-select',verbs.findIndex(x=>x.id==='가다'));b.toggles.find(x=>x.dataset.element==='time').click();assert.equal(b.get('translation').textContent,'My friend goes');
select('subject-select',subjects.findIndex(x=>x.kr==='부모님은'));assert.equal(b.get('translation').textContent,'My parents go');
select('verb-select',verbs.findIndex(x=>x.id==='하다'));b.toggles.find(x=>x.dataset.element==='question').click();assert.equal(b.get('translation').textContent,'What do my parents do?');select('subject-select',subjects.findIndex(x=>x.kr==='친구는'));assert.equal(b.get('translation').textContent,'What does my friend do?');
b=await boot('describe-builder.js');for(let i=0;i<data.describe.adjectives.length-1;i++)b.get('block-adjective').click();const options=b.get('subject-select').children.map(x=>x.textContent);for(const form of ['가족이','부모님이','친구가'])assert.ok(options.some(x=>x.startsWith(form)));console.log('PASS: 11 studied subjects; direct selection/cycle; exact 3 requested questions; what-question restrictions; correct 은/는 and 이/가; phrase-audio API')})().catch(e=>{console.error(e);process.exit(1)});
